# Generated by Django 6.0.1 on 2026-02-03 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato_tecnico', models.CharField(blank=True, max_length=255)),
                ('gestor_responsavel', models.CharField(blank=True, max_length=255)),
                ('area', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=50)),
                ('data_incidente', models.DateField(blank=True, null=True)),
                ('equipe_seguranca', models.CharField(blank=True, max_length=10)),
                ('descoberta', models.CharField(blank=True, max_length=50)),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('hosts_afetados', models.IntegerField(blank=True, null=True)),
                ('localidade', models.CharField(blank=True, max_length=50)),
                ('tecnologia_rede', models.CharField(blank=True, max_length=50)),
                ('qtd_links', models.IntegerField(blank=True, null=True)),
                ('vpn', models.CharField(blank=True, max_length=50)),
                ('ambiente', models.CharField(blank=True, max_length=50)),
                ('servico_afetado', models.CharField(blank=True, max_length=255)),
                ('sistema_operacional', models.CharField(blank=True, max_length=255)),
                ('versao', models.CharField(blank=True, max_length=100)),
                ('ip', models.CharField(blank=True, max_length=50)),
                ('status_incidente', models.CharField(blank=True, max_length=50)),
                ('descricao_incidente', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
